import {
  createDraftPlan,
  createProofCard,
  type ClientProfile,
  type CheckIn,
  type PaymentSubscription,
  type ProgramPlan,
  type ProofCard
} from "@coachos/domain";
import type { CoachOsConfig } from "./config";
import Bytez from "bytez.js";

export interface PlanGenerationProvider {
  readonly name: string;
  generateDraft(client: ClientProfile, coachId: string): Promise<ProgramPlan> | ProgramPlan;
}

export interface ProofCardProvider {
  readonly name: string;
  build(client: ClientProfile, latestCheckIn?: CheckIn): ProofCard;
}

export interface BillingProvider {
  readonly name: string;
  createImportedSubscription(client: ClientProfile): PaymentSubscription;
  applyWebhookUpdate(
    subscriptions: PaymentSubscription[],
    clientId: string,
    status: "active" | "past_due" | "cancelled"
  ): PaymentSubscription[];
  summarize(subscriptions: PaymentSubscription[]): {
    subscriptions: PaymentSubscription[];
    mrrGbp: number;
    churnRiskCount: number;
  };
}

export class MockPlanGenerationProvider implements PlanGenerationProvider {
  readonly name = "mock-openai";

  generateDraft(client: ClientProfile, coachId: string) {
    return createDraftPlan(client, coachId);
  }
}

export class SimulatedOpenAIPlanGenerationProvider implements PlanGenerationProvider {
  readonly name: string;

  constructor(private readonly model: string) {
    this.name = `simulated-openai:${model}`;
  }

  generateDraft(client: ClientProfile, coachId: string) {
    const draft = createDraftPlan(client, coachId);
    return {
      ...draft,
      latestVersion: {
        ...draft.latestVersion,
        explanation: [
          `Simulated OpenAI provider using model ${this.model}.`,
          ...draft.latestVersion.explanation
        ]
      }
    };
  }
}

export class DeepSeekPlanGenerationProvider implements PlanGenerationProvider {
  readonly name = "deepseek-api";
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  private sdk: any;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  private aiModel: any;

  constructor(apiKey: string) {
    this.sdk = new Bytez(apiKey);
    this.aiModel = this.sdk.model("deepseek-ai/DeepSeek-V3.1");
  }

  async generateDraft(client: ClientProfile, coachId: string): Promise<ProgramPlan> {
    const prompt = `You are an expert fitness coach AI. Create a personalised weekly coaching plan for the following client.
Client Name: ${client.fullName}
Client Goal: ${client.goal}
Adherence Score: ${client.adherenceScore}%

Return ONLY valid JSON (no markdown, no code blocks) in this exact format:
{
  "title": "3-4 word descriptive plan title",
  "explanation": ["Reason 1 for this plan choice", "Reason 2 based on client goal and adherence"],
  "workouts": ["Session 1 description", "Session 2 description", "Session 3 description"],
  "nutrition": ["Nutrition goal 1", "Nutrition goal 2", "Nutrition goal 3"]
}`;
    const results = await this.aiModel.run([{ role: "user", content: prompt }]);
    if (results.error) throw new Error(String(results.error));

    let text: string = results.output.content.trim();
    // Strip markdown code fences if present
    text = text.replace(/^```(?:json)?\n?/i, "").replace(/\n?```$/i, "").trim();

    let parsed: { title?: string; explanation?: string[]; workouts?: string[]; nutrition?: string[] };
    try {
      parsed = JSON.parse(text);
    } catch {
      console.warn("[DeepSeek] JSON parse failed, using fallback. Raw:", text.slice(0, 200));
      const fallback = createDraftPlan(client, coachId);
      return { ...fallback, latestVersion: { ...fallback.latestVersion, explanation: ["AI plan generated with DeepSeek-V3.1", ...fallback.latestVersion.explanation] } };
    }

    const baseId = `plan_${client.id}_ds${Date.now()}`;
    return {
      id: baseId,
      clientId: client.id,
      coachId,
      title: parsed.title || "DeepSeek Coaching Plan",
      latestVersion: {
        id: `${baseId}_v1`,
        planId: baseId,
        versionNumber: 1,
        status: "draft",
        explanation: parsed.explanation?.length ? parsed.explanation : ["Generated by DeepSeek-V3.1 via Bytez"],
        workouts: parsed.workouts?.length ? parsed.workouts : ["3 strength sessions per week"],
        nutrition: parsed.nutrition?.length ? parsed.nutrition : ["High protein, calorie deficit"],
        updatedAt: new Date().toISOString()
      }
    };
  }
}


export class MockProofCardProvider implements ProofCardProvider {
  readonly name = "mock-proof-engine";

  build(client: ClientProfile, latestCheckIn?: CheckIn) {
    return createProofCard(client, latestCheckIn);
  }
}

export class SimulatedProofCardProvider implements ProofCardProvider {
  readonly name = "simulated-proof-engine";

  build(client: ClientProfile, latestCheckIn?: CheckIn) {
    const proof = createProofCard(client, latestCheckIn);
    return {
      ...proof,
      headline: `${proof.headline} [Simulated share-ready card]`
    };
  }
}

export class MockBillingProvider implements BillingProvider {
  readonly name = "mock-stripe";

  createImportedSubscription(client: ClientProfile): PaymentSubscription {
    return {
      id: `sub_${client.id}`,
      clientId: client.id,
      status: "trialing",
      amountGbp: client.monthlyPriceGbp,
      renewalDate: client.nextRenewalDate
    };
  }

  applyWebhookUpdate(
    subscriptions: PaymentSubscription[],
    clientId: string,
    status: "active" | "past_due" | "cancelled"
  ) {
    return subscriptions.map((subscription) =>
      subscription.clientId === clientId ? { ...subscription, status } : subscription
    );
  }

  summarize(subscriptions: PaymentSubscription[]) {
    return {
      subscriptions,
      mrrGbp: subscriptions
        .filter((subscription) => subscription.status === "active")
        .reduce((sum, subscription) => sum + subscription.amountGbp, 0),
      churnRiskCount: subscriptions.filter((subscription) => subscription.status === "past_due").length
    };
  }
}

export class SimulatedStripeBillingProvider implements BillingProvider {
  readonly name: string;

  constructor(private readonly mode: "test" | "live") {
    this.name = `simulated-stripe:${mode}`;
  }

  createImportedSubscription(client: ClientProfile): PaymentSubscription {
    return {
      id: `sim_sub_${client.id}`,
      clientId: client.id,
      status: "trialing",
      amountGbp: client.monthlyPriceGbp,
      renewalDate: client.nextRenewalDate
    };
  }

  applyWebhookUpdate(
    subscriptions: PaymentSubscription[],
    clientId: string,
    status: "active" | "past_due" | "cancelled"
  ) {
    return subscriptions.map((subscription) =>
      subscription.clientId === clientId ? { ...subscription, status } : subscription
    );
  }

  summarize(subscriptions: PaymentSubscription[]) {
    return {
      subscriptions,
      mrrGbp: subscriptions
        .filter((subscription) => subscription.status === "active")
        .reduce((sum, subscription) => sum + subscription.amountGbp, 0),
      churnRiskCount: subscriptions.filter((subscription) => subscription.status === "past_due").length
    };
  }
}

export type DemoServiceAdapters = {
  planGeneration: PlanGenerationProvider;
  proofCards: ProofCardProvider;
  billing: BillingProvider;
};

export function createMockServiceAdapters(): DemoServiceAdapters {
  return {
    planGeneration: new MockPlanGenerationProvider(),
    proofCards: new MockProofCardProvider(),
    billing: new MockBillingProvider()
  };
}

export function createServiceAdapters(config: CoachOsConfig): DemoServiceAdapters {
  const aiProvider = process.env.COACHOS_AI_PROVIDER ?? config.aiProvider;
  const bytezKey = process.env.BYTEZ_API_KEY;
  if (aiProvider === "deepseek" && !bytezKey) {
    throw new Error("BYTEZ_API_KEY environment variable is required when COACHOS_AI_PROVIDER=deepseek");
  }

  let planGeneration: PlanGenerationProvider;
  if (aiProvider === "deepseek") {
    planGeneration = new DeepSeekPlanGenerationProvider(bytezKey as string);
  } else if (aiProvider === "simulated-openai") {
    planGeneration = new SimulatedOpenAIPlanGenerationProvider(config.openAiModel);
  } else {
    planGeneration = new MockPlanGenerationProvider();
  }

  return {
    planGeneration,
    proofCards:
      config.proofProvider === "simulated-proof"
        ? new SimulatedProofCardProvider()
        : new MockProofCardProvider(),
    billing:
      config.billingProvider === "simulated-stripe"
        ? new SimulatedStripeBillingProvider(config.stripeMode)
        : new MockBillingProvider()
  };
}
